name: Add manual trigger
on:
  workflow_dispatch

jobs:
  job_id:
     name: a
     runs-on: ubuntu-latest
     steps:
       - name: ls  
         run: |
           ls 
           pwd 
           uname 
