name: CI 
on:
  push: 
  pull_request:
    
jobs:
  job_ci:
    runs-on: ubuntu-latest
    name: npm install 
    steps: 


     - name: Checkout code 
       uses: actions/checkout@v2 
       with:
        depth: 1

     - name: setup node enviroment
       uses: actions/setup-node@v2
       with:
        node-version: '14'

    
     - name: Build and test
       run: |
        npm install
        npm test
        pwd 
        ls -l 



